### ISSUE TITLE
Table doesn’t exist error message on ext settings page

### ISSUE THREAD

**Issue by Galixte** [pierrdu/lmdi_multilinks#1]
Hi @pierrdu,

I encounter this error message after installing your extension when I click on the setting page from the EXTENSION Tab:
```
Erreur générale
SQL ERROR [ mysqli ]

Table 'nombdd.phpbb_lmdi_multilinks' doesn't exist [1146]

SQL

SELECT * FROM phpbb_lmdi_multilinks WHERE ppap = 0 ORDER BY enabled DESC

BACKTRACE

FILE: (not given by php)
LINE: (not given by php)
CALL: msg_handler()

FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 997
CALL: trigger_error()

FILE: [ROOT]/phpbb/db/driver/mysqli.php
LINE: 193
CALL: phpbb\db\driver\driver->sql_error()

FILE: [ROOT]/phpbb/db/driver/factory.php
LINE: 329
CALL: phpbb\db\driver\mysqli->sql_query()

FILE: [ROOT]/ext/lmdi/multilinks/acp/multilinks_module.php
LINE: 211
CALL: phpbb\db\driver\factory->sql_query()

FILE: [ROOT]/ext/lmdi/multilinks/acp/multilinks_module.php
LINE: 188
CALL: lmdi\multilinks\acp\multilinks_module->assign_block_vars()

FILE: [ROOT]/includes/functions_module.php
LINE: 676
CALL: lmdi\multilinks\acp\multilinks_module->main()

FILE: [ROOT]/adm/index.php
LINE: 82
CALL: p_master->load_active()
```

**Comment by pierrdu** [comment]
Bonjour,
La table n'a pas été créée lors de l'installation ? Peux-tu regarder dans la base ?

**Comment by Galixte** [comment]
Hi @pierrdu,

non pas de table ```phpbb_lmdi_multilinks``` créée.

**Comment by pierrdu** [comment]
C'est la première fois que je vois ce genre d'erreur. Avais-tu déjà installé l'extension sans la désinstaller correctement ? Regarde dans la table phpbb_migrations si tu as une ligne avec migration_name contenant multilinks. Si tel est le cas, tu peux la supprimer et recommencer l'installation.

**Comment by Galixte** [comment]
Salut @pierrdu,

non je ne l’avais pas installée auparavant. Ce constat a été effectué depuis une installation fraiche de phpBB 3.2.5 sous PHP 7.0.x, 7.1.x & 7.2.x.

La ligne dont tu fais mention est bien présente lorsque l’extension est installée, dès lors que je la désinstalle la ligne disparait.

Pour la colonne « migration_name » j’ai la valeur suivante : ```\lmdi\multilinks\migrations\migration_1```
Pour la colonne « migration_depends_on » j’ai la valeur suivante : ```a:1:{i:0;s:36:"\phpbb\db\migration\data\v310\alpha2";}```

Aussi, j’ai bien tenté de supprimer la ligne indiquée puis de réinstaller l’extension mais j’ai la même erreur que précédemment lors des mêmes circonstances.

**Comment by pierrdu** [comment]
Je ne comprends pas pourquoi le fichier de migration s'exécute sans créer la table. Je vais t'envoyer un dump d'une mini-table. Essaie de l'exécuter pour voir comment il se fait que ta machine refuse de créer la table.
