### ISSUE TITLE
PHP Warning

### ISSUE THREAD

**Issue by E30man** [pierrdu/lmdi_multilinks#2]
I get a error message when enabling the extension, I gather it something to do with running 7.2.16?
 
[phpBB Debug] PHP Warning: in file [ROOT]/ext/lmdi/multilinks/event/listener.php on line 98: count(): Parameter must be an array or an object that implements Countable

Thanks

**Comment by pierrdu** [comment]
Exactly.
You should step down your version of PHP.

**Comment by E30man** [comment]
Thanks for the reply, what version would you recommend?

**Comment by pierrdu** [comment]
I'm still with 7.1.6. I plan to step up when phpBB version 3.3 comes out.
