### ISSUE TITLE
"Extension .yml file check extension" throws an invalid file with lastest version

### ISSUE THREAD

**Issue by LukasThyWalls** [pierrdu/lmdi_multilinks#3]
Hello

I was going to test your extension in a 3.3.0 installation, but as a security measure, and knowing it isn't failproof, i normally check the new extensions with "Extension .yml file check extension" https://github.com/david63/extservicescheck, firstly for old extensions for 3.1.x and 3.2.x which can be usable in 3.3.0 only checking and fixing the extensions .yml syntax (not all ext. works, of course, but in my little knowledge it was very useful)

The issue is when i uploaded the last version of LMDI Multilinks, the "Extension .yml file check extension" throws me an error with it:

```
[This extension appears to have errors] LMDI Multilinks (lmdi 2.2.6 Dormant)

[OK] The services.yml file is valid
[X] The tables.yml file is invalid

Original file

parameters:
    lmdi.multilinks.tables.multilinks: %core.table_prefix%lmdi_multilinks

Reformatted file

parameters:
 lmdi.multilinks.tables.multilinks: '%core.table_prefix%lmdi_multilinks'
```

The extension shows what can be changed to meet phpbb 3.3.0 requeriments.
This is correct? Should i change it? I was thinking your 2.2.6 version is PHPBB 3.3.0 compatible.

Thanks.

**Comment by pierrdu** [comment]
My bad!
I made all those changes for all my extensions, but this one was not updated.
