### ISSUE TITLE
Suggestion: add option to hide links in mobile view

### ISSUE THREAD

**Issue by Peterr-K** [pierrdu/lmdi_multilinks#4]
Hi

thank you very much for your great extentions! 👍 I have two suggetions:

1. If possible, please add option to the links to hide the link in the mobile view, thanks.

2. if possible, can be "Links added at the end of the navigation bar" showed at the end of the quick menu in mobile view? I want to solve the problem, when I want have users links Your posts, New posts, Unread posts etc have at the top of mobile menu, not below Multilinks.

thank you very much!

![image](https://user-images.githubusercontent.com/56595831/96829495-151fdb00-143a-11eb-8b79-08d677ae17b1.png)

**Comment by pierrdu** [comment]
To hide the links in mobile view, a solution would be to add class="multilinks" in the 'li' items (files overall_header_navigation_append.html and ~~~prepend.html, to create a multilinks.csss file containing an empty class multilinks and a '@media only screen' line for the width you want with 'display: none;'.
Your second idea would be more difficult to implement.

**Comment by pierrdu** [comment]
It was so easy that I did code the solution and uploaded a new version 2.27.

**Comment by Peterr-K** [comment]
Ok thank You, and hopefully this hidding in mobile view will be in future added as per link setting. bye 👍 

![E8CA628F-D60A-4674-AEC5-8291E647966A](https://user-images.githubusercontent.com/56595831/96862937-6e056880-1466-11eb-9b6e-39da73f1b18a.jpeg)
