### ISSUE TITLE
Blank page on accessing settings

### ISSUE THREAD

**Issue by WimVDK** [pierrdu/lmdi_multilinks#6]
While the latest master from github can be enabled on phpbb 3.3.8, accessing the settings page renders a blank page, effectively making the extension inoperable.

**Comment by pierrdu** [comment]
I can't reproduce the problem with this version (french or british package). Do you happen to use another language?

**Comment by WimVDK** [comment]
uk phpbb, nl language pack

Tried enabling debug mode according to https://www.phpbb.com/support/docs/en/3.3/kb/article/enabling-debug-mode/ but that doesn't help on the backend. Only shows the following on the front-end

`[phpBB Debug] PHP Warning: in file [ROOT]/vendor/symfony/config/FileLocator.php on line 60: file_exists(): open_basedir restriction in effect. File([ROOT]/../../default/routing/routing.yml) is not within the allowed path(s): (/var/www/vhosts/sitename.tld/:/tmp/](http://sitename.tld/:/tmp/))
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions.php on line 4149: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:3027)
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions.php on line 4149: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:3027)
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions.php on line 4149: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:3027)
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions.php on line 4149: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:3027)`

Even removing the fr language pack doesn't help

Edit: Enabled php errors. Found the culprit

`Fatal error: Uncaught Error: Cannot access protected property lmdi\multilinks\acp\multilinks_module::$tpl_name in /var/www/vhosts/sitename.tld/httpdocs/includes/functions_module.php:964) Stack trace: #0 /var/www/vhosts/sitename.tld/httpdocs/adm/index.php(87):) p_master->get_tpl_name() #1 {main} thrown in /var/www/vhosts/sitename.tld/httpdocs/includes/functions_module.php) on line 964`

hope it helps

**Comment by pierrdu** [comment]
I don't understand. A line déleted in the latest update was still there in the file acp/multilinks_module.php. The line protected $tpl_name; should be deleted. I uploaded a version 2.2.13.

**Comment by WimVDK** [comment]
Fix confirmed, Settings page now accessible!

**Comment by pierrdu** [comment]
Fine. Thanks for the confirmation.
